### ISSUE TITLE
Vagrant up produces error

### ISSUE THREAD

**Issue by chriskinsman** [Azure/service-fabric-linux-vagrant-onebox#3]
OSX Sierra
Vagrant 1.8.7

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'azureservicefabric/dev.tp6' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'azureservicefabric/dev.tp6' (v0) for provider: virtualbox
    default: Downloading: http://download.microsoft.com/download/5/4/3/543A221C-DBB6-472D-97EA-5A62F0165748/azureservicefabric.tp6.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

**Comment by mani-ramaswamy** [comment]
Hi Chris,

We're not able to reproduce it. The problem is likely the network getting disconnected, since the image is fairly large and includes the complete Java and C# SDK with dependencies  (~ 1.5GB). Another option is to download the image from the link above and then updating your local vagrant file to point to that image (i.e., just providing the box as opposed to the image URL).

Alternatively, you can install the setup yourself (esp. if you don't need the entire SDK) on a Linux VM using the instructions @ https://azure.microsoft.com/en-us/documentation/articles/service-fabric-get-started-linux/

Please let me know if that works. We'll also simultaneously try to look for opportunities to reduce the size of the image. 

Best,
Mani
